// guess the number


// function GuessingGame() {
//     let computer = Math.floor(Math.random() * (100 - 1) + 1);
//     let guess = 0;
//     user = parseInt(prompt("Enter your number (1-100)"));
//     while (user != computer) {
//         user = parseInt(prompt("Enter your number(1-100)"));
//         guess++;
//         if (user === computer) {
//             alert(`Your Win! In ${guess} guess`);
//             break;
//         } else if (user > computer) {
//             alert("Enter lower Number");
//         }
//         else {
//             alert("Enter Higher Number");
//         }

//     }
// }
// GuessingGame();

// program where the user has to guess a number generated by a program

// function guessNumber() {
//     // generating a random integer from 1 to 10
//     const random = Math.floor(Math.random() * 10) + 1;

//     // take input from the user
//     let number = parseInt(prompt('Guess a number from 1 to 10: '));

//     // take the input until the guess is correct
//     while (number != random) {
//         number = parseInt(prompt('Guess a number from 1 to 10: '));
//         // check if the guess is correct
//         if (number === random) {
//             alert('You guessed the correct number is:', number);

//         } else if (number > random) {
//             alert("Entered number is too big")

//         } else {
//             alert("Entered number is too small")

//         }
//     }

// }
// // call the function
// guessNumber();



// let num = parseInt(prompt("enter the value"));
// let myName = 0;
// while (num != 0) {
//     let num = parseInt(prompt("enter the value"));
//     myName++;

//     if (num == 0) {
//         console.log("my name repeted at :", myName);
//         break;
//     }
// }
